---
- name: Install monitoring stack
  become: true
  become_user: root
  become_method: sudo
  hosts: monitor
  roles:
    - role: grafana
      tags: [grafana]
    - role: prometheus
      tags: [prometheus]
    - role: alertmanager
      tags: [alertmanager]

- name: Install nginx
  become: true
  hosts: db
  roles:
    - role: nginx
      tags: [nginx]

- name: install node-exporter
  hosts: web, db
  become: true
  roles:
    - role: node-exporter
      tags: [node-exporter]     
