---
# tasks file for roles/alertmanager
- name: Creating alertmanager user group
  group: name="{{groupId}}"
  become: true
- name: Creating alertmanager user
  user:
    name: "{{userId}}"
    group: "{{groupId}}"
    system: yes
    shell: "/sbin/nologin"
    comment: "{{userId}} nologin User"
    createhome: "no"
    state: present

- name: Create a directory for downloaded file
  file:
    path: /home/Alertmanager
    state: directory

# - name: Download alertmanager
#   get_url:
#     url: "https://github.com/prometheus/alertmanager/releases/download/v{{ version }}/alertmanager-{{ version }}.linux-amd64.tar.gz"
#     dest: /home/Alertmanager
#     force : no
#   register: download_alertmanager
    

# - name: Extract alertmanager
#   unarchive:
#     src: /home/Alertmanager/alertmanager-{{ version }}.linux-amd64.tar.gz
#     dest: /home/Alertmanager
#     # creates : "/home/Alertmanager/AM"
#     remote_src: yes
#   when: download_alertmanager.changed

- name: Copy alertmanager executable to bin
  copy:
    src: "/home/Alertmanager/alertmanager-{{ version }}.linux-amd64/alertmanager"
    dest: "/usr/local/bin/alertmanager"
    owner: "{{userId}}"
    group: "{{groupId}}"
    remote_src: yes
    mode: 0755

- name: Delete alertmanager tmp folder
  file:
    path: '/home/Alertmanager-{{ version }}.linux-amd64'
    state: absent
  
- name: create the config file  location/directory
  file:
    path: /etc/alertmanager
    state: directory
    owner: alertmanager
    group: alertmanager

- name: create the storage file location/directory
  file:
    path: /etc/alertmanager/data
    state: directory
    owner: alertmanager
    group: alertmanager

- name: Copy config file
  copy:
    src: "alertmanager.yml"
    dest: /etc/alertmanager/alertmanager.yml
    
- name: Copy systemd init file
  template:
    src: alertmngr.conf
    dest: /etc/systemd/system/alertmanager.service
  notify: systemd_reload

- name: Start alertmanager service
  service:
    name: alertmanager
    state: started
    enabled: yes
# - name: Check if alertmanager is accessible
#   uri:
#     url: http://localhost:9093
#     method: GET
#     status_code: 200


